export const ASCII = [
	'NULL', // ( Null character )
	'SOH', // ( Start of Header )
	'STX', // ( Start of Text )
	'ETX', // ( End of Text, hearts card suit )
	'EOT', // ( End of Transmission, diamonds card suit )
	'ENQ', // ( Enquiry, clubs card suit )
	'ACK', // ( Acknowledgement, spade card suit )
	'BEL', // ( Bell )
	'BS', // ( Backspace )
	'HT', // ( Horizontal Tab )
	'LF', // ( Line feed )
	'VT', // ( Vertical Tab, male symbol, symbol for Mars )
	'FF', // ( Form feed, female symbol, symbol for Venus )
	'CR', // ( Carriage return )
	'SO', // ( Shift Out )
	'SI', // ( Shift In )
	'DLE', // ( Data link escape )
	'DC1', // ( Device control 1 )
	'DC2', // ( Device control 2 )
	'DC3', // ( Device control 3 )
	'DC4', // ( Device control 4 )
	'NAK', // ( NAK Negative-acknowledge )
	'SYN', // ( Synchronous idle )
	'ETB', // ( End of trans. block )
	'CAN', // ( Cancel )
	'EM', // ( End of medium )
	'SUB', // ( Substitute )
	'ESC', // ( Escape )
	'FS', // ( File separator )
	'GS', // ( Group separator )
	'RS', // ( Record separator )
	'US', // ( Unit separator )
	'space', // ( Space )
	'!',// ( Exclamation mark )
	'"',// ( Double quotes ; Quotation mark ; speech marks )
	'#',// ( Number sign )
	'$',// ( Dollar sign )
	'%',// ( Percent sign )
	'&',// ( Ampersand )
	"'",// ( Single quote or Apostrophe )
	'(',// ( round brackets or parentheses, opening round bracket )
	')',// ( parentheses or round brackets, closing parentheses )
	'*',// ( Asterisk )
	'+',// ( Plus sign )
	',',// ( Comma )
	'-',// ( Hyphen , minus sign )
	'.',// ( Dot, full stop )
	'/',// ( Slash , forward slash , fraction bar , division slash )
	'0', // ( number zero )
	'1', // ( number one )
	'2', // ( number two )
	'3', // ( number three )
	'4', // ( number four )
	'5', // ( number five )
	'6', // ( number six )
	'7', // ( number seven )
	'8', // ( number eight )
	'9', // ( number nine )
	':',// ( Colon )
	';',// ( Semicolon )
	'<',// ( Less-than sign )
	'=',// ( Equals sign )
	'>',// ( Greater-than sign ; Inequality )
	'?',// ( Question mark )
	'@',// ( At sign )
	'A', // ( Capital letter A )
	'B', // ( Capital letter B )
	'C', // ( Capital letter C )
	'D', // ( Capital letter D )
	'E', // ( Capital letter E )
	'F', // ( Capital letter F )
	'G', // ( Capital letter G )
	'H', // ( Capital letter H )
	'I', // ( Capital letter I )
	'J', // ( Capital letter J )
	'K', // ( Capital letter K )
	'L', // ( Capital letter L )
	'M', // ( Capital letter M )
	'N', // ( Capital letter N )
	'O', // ( Capital letter O )
	'P', // ( Capital letter P )
	'Q', // ( Capital letter Q )
	'R', // ( Capital letter R )
	'S', // ( Capital letter S )
	'T', // ( Capital letter T )
	'U', // ( Capital letter U )
	'V', // ( Capital letter V )
	'W', // ( Capital letter W )
	'X', // ( Capital letter X )
	'Y', // ( Capital letter Y )
	'Z', // ( Capital letter Z )
	'[',// ( square brackets or box brackets, opening bracket )
	'\\',// ( Backslash , reverse slash )
	']',// ( box brackets or square brackets, closing bracket )
	'^',// ( Circumflex accent or Caret )
	'_', // ( underscore , understrike , underbar or low line )
	'`',// ( Grave accent )
	'a', // ( Lowercase letter a , minuscule a )
	'b', // ( Lowercase letter b , minuscule b )
	'c', // ( Lowercase letter c , minuscule c )
	'd', // ( Lowercase letter d , minuscule d )
	'e', // ( Lowercase letter e , minuscule e )
	'f', // ( Lowercase letter f , minuscule f )
	'g', // ( Lowercase letter g , minuscule g )
	'h', // ( Lowercase letter h , minuscule h )
	'i', // ( Lowercase letter i , minuscule i )
	'j', // ( Lowercase letter j , minuscule j )
	'k', // ( Lowercase letter k , minuscule k )
	'l', // ( Lowercase letter l , minuscule l )
	'm', // ( Lowercase letter m , minuscule m )
	'n', // ( Lowercase letter n , minuscule n )
	'o', // ( Lowercase letter o , minuscule o )
	'p', // ( Lowercase letter p , minuscule p )
	'q', // ( Lowercase letter q , minuscule q )
	'r', // ( Lowercase letter r , minuscule r )
	's', // ( Lowercase letter s , minuscule s )
	't', // ( Lowercase letter t , minuscule t )
	'u', // ( Lowercase letter u , minuscule u )
	'v', // ( Lowercase letter v , minuscule v )
	'w', // ( Lowercase letter w , minuscule w )
	'x', // ( Lowercase letter x , minuscule x )
	'y', // ( Lowercase letter y , minuscule y )
	'z', // ( Lowercase letter z , minuscule z )
	'{',// ( braces or curly brackets, opening braces )
	'|',// ( vertical-bar, vbar, vertical line or vertical slash )
	'}',// ( curly brackets or braces, closing curly brackets )
	'~',// ( Tilde ; swung dash )
	'DEL', // ( Delete )
];